package com.unmsm.sisprov.entity;
// Generated 15-ago-2020 14:53:39 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "Categoria", schema = "public")
public class Categoria implements java.io.Serializable {

	private int idCategoria;
	private String nombreCat;
	private String descripCat;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Categoria() {
	}

	public Categoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public Categoria(int idCategoria, String nombreCat, String descripCat, Set<Producto> productos) {
		this.idCategoria = idCategoria;
		this.nombreCat = nombreCat;
		this.descripCat = descripCat;
		this.productos = productos;
	}

	@Id

	@Column(name = "idCategoria", unique = true, nullable = false)
	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "nombre_cat", length = 45)
	public String getNombreCat() {
		return this.nombreCat;
	}

	public void setNombreCat(String nombreCat) {
		this.nombreCat = nombreCat;
	}

	@Column(name = "descrip_cat", length = 200)
	public String getDescripCat() {
		return this.descripCat;
	}

	public void setDescripCat(String descripCat) {
		this.descripCat = descripCat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}