package com.unmsm.sisprov.entity;
// Generated 15-ago-2020 14:53:39 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "Producto", schema = "public")
public class Producto implements java.io.Serializable {

	private int idProducto;
	private Categoria categoria;
	private String nombre;
	private String descripcion;
	private Integer stock;
	private String img;
	private BigDecimal precio;
	private Set<Proformadetalle> proformadetalles = new HashSet<Proformadetalle>(0);

	public Producto() {
	}

	public Producto(int idProducto, Categoria categoria) {
		this.idProducto = idProducto;
		this.categoria = categoria;
	}

	public Producto(int idProducto, Categoria categoria, String nombre, String descripcion, Integer stock, String img,
			BigDecimal precio, Set<Proformadetalle> proformadetalles) {
		this.idProducto = idProducto;
		this.categoria = categoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.stock = stock;
		this.precio = precio;
		this.img = img;
		this.proformadetalles = proformadetalles;
	}

	@Id

	@Column(name = "idProducto", unique = true, nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_prod", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "precio", precision = 10)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}
	
	@Column(name = "img", length = 200)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Proformadetalle> getProformadetalles() {
		return this.proformadetalles;
	}

	public void setProformadetalles(Set<Proformadetalle> proformadetalles) {
		this.proformadetalles = proformadetalles;
	}

}
