package com.unmsm.sisprov.entity;
// Generated 15-ago-2020 14:53:39 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proforma generated by hbm2java
 */
@Entity
@Table(name = "Proforma", schema = "public")
public class Proforma implements java.io.Serializable {

	private int idProforma;
	private String cliente;
	private Date fecha;
	private BigDecimal montoTotal;
	private Set<Proformadetalle> proformadetalles = new HashSet<Proformadetalle>(0);

	public Proforma() {
	}

	public Proforma(int idProforma) {
		this.idProforma = idProforma;
	}

	public Proforma(int idProforma, String cliente, Date fecha, BigDecimal montoTotal,
			Set<Proformadetalle> proformadetalles) {
		this.idProforma = idProforma;
		this.cliente = cliente;
		this.fecha = fecha;
		this.montoTotal = montoTotal;
		this.proformadetalles = proformadetalles;
	}

	@Id

	@Column(name = "idProforma", unique = true, nullable = false)
	public int getIdProforma() {
		return this.idProforma;
	}

	public void setIdProforma(int idProforma) {
		this.idProforma = idProforma;
	}

	@Column(name = "cliente", length = 50)
	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "montoTotal", precision = 10)
	public BigDecimal getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(BigDecimal montoTotal) {
		this.montoTotal = montoTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proforma")
	public Set<Proformadetalle> getProformadetalles() {
		return this.proformadetalles;
	}

	public void setProformadetalles(Set<Proformadetalle> proformadetalles) {
		this.proformadetalles = proformadetalles;
	}

}