package com.unmsm.sisprov.entity;
// Generated 15-ago-2020 14:53:39 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Proformadetalle generated by hbm2java
 */
@Entity
@Table(name = "ProformaDetalle", schema = "public")
public class Proformadetalle implements java.io.Serializable {

	private ProformadetalleId id;
	private Producto producto;
	private Proforma proforma;
	private BigDecimal submonto;
	private int cantidad;

	public Proformadetalle() {
	}

	public Proformadetalle(ProformadetalleId id, Producto producto, Proforma proforma) {
		this.id = id;
		this.producto = producto;
		this.proforma = proforma;
	}

	public Proformadetalle(ProformadetalleId id, Producto producto, Proforma proforma, BigDecimal submonto) {
		this.id = id;
		this.producto = producto;
		this.proforma = proforma;
		this.submonto = submonto;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codProd", column = @Column(name = "cod_prod", nullable = false)),
			@AttributeOverride(name = "codProforma", column = @Column(name = "cod_proforma", nullable = false)) })
	public ProformadetalleId getId() {
		return this.id;
	}

	public void setId(ProformadetalleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_prod", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proforma", nullable = false, insertable = false, updatable = false)
	public Proforma getProforma() {
		return this.proforma;
	}

	public void setProforma(Proforma proforma) {
		this.proforma = proforma;
	}

	@Column(name = "submonto", precision = 10)
	public BigDecimal getSubmonto() {
		return this.submonto;
	}

	public void setSubmonto(BigDecimal submonto) {
		this.submonto = submonto;
	}
	
	@Column(name = "cantidad")
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
