package com.unmsm.sisprov.entity;
// Generated 15-ago-2020 14:53:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProformadetalleId generated by hbm2java
 */
@Embeddable
public class ProformadetalleId implements java.io.Serializable {

	private int codProd;
	private int codProforma;

	public ProformadetalleId() {
	}

	public ProformadetalleId(int codProd, int codProforma) {
		this.codProd = codProd;
		this.codProforma = codProforma;
	}

	@Column(name = "cod_prod", nullable = false)
	public int getCodProd() {
		return this.codProd;
	}

	public void setCodProd(int codProd) {
		this.codProd = codProd;
	}

	@Column(name = "cod_proforma", nullable = false)
	public int getCodProforma() {
		return this.codProforma;
	}

	public void setCodProforma(int codProforma) {
		this.codProforma = codProforma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProformadetalleId))
			return false;
		ProformadetalleId castOther = (ProformadetalleId) other;

		return (this.getCodProd() == castOther.getCodProd()) && (this.getCodProforma() == castOther.getCodProforma());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProd();
		result = 37 * result + this.getCodProforma();
		return result;
	}

}
